# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_pl1_ax_replies <- function(ax, na1, na2) {
    .Call(`_RelationalContractsCpp_c_pl1_ax_replies`, ax, na1, na2)
}

c_pl2_ax_replies <- function(ax, na1, na2) {
    .Call(`_RelationalContractsCpp_c_pl2_ax_replies`, ax, na1, na2)
}

c_pl1_best_reply_ax <- function(u_ax, ax, na1, na2) {
    .Call(`_RelationalContractsCpp_c_pl1_best_reply_ax`, u_ax, ax, na1, na2)
}

c_pl2_best_reply_ax <- function(u_ax, ax, na1, na2) {
    .Call(`_RelationalContractsCpp_c_pl2_best_reply_ax`, u_ax, ax, na1, na2)
}

c_pl2_ax_best_replies <- function(u_ax, nai, naj, nx) {
    .Call(`_RelationalContractsCpp_c_pl2_ax_best_replies`, u_ax, nai, naj, nx)
}

c_pl1_ax_best_reply_payoffs <- function(u_ax, nai, naj, nx) {
    .Call(`_RelationalContractsCpp_c_pl1_ax_best_reply_payoffs`, u_ax, nai, naj, nx)
}

c_pl2_ax_best_reply_payoffs <- function(u_ax, nai, naj, nx) {
    .Call(`_RelationalContractsCpp_c_pl2_ax_best_reply_payoffs`, u_ax, nai, naj, nx)
}

c_chunk_sums <- function(vec, sizes) {
    .Call(`_RelationalContractsCpp_c_chunk_sums`, vec, sizes)
}

c_chunk_maxs <- function(vec, sizes) {
    .Call(`_RelationalContractsCpp_c_chunk_maxs`, vec, sizes)
}

c_which_chunk_maxs <- function(vec, sizes) {
    .Call(`_RelationalContractsCpp_c_which_chunk_maxs`, vec, sizes)
}

mat_times_vec_rows <- function(mat, vec, vec_rows, target_nrow) {
    .Call(`_RelationalContractsCpp_mat_times_vec_rows`, mat, vec, vec_rows, target_nrow)
}

mat_times_vec <- function(mat, vec, target_nrow = 0L) {
    .Call(`_RelationalContractsCpp_mat_times_vec`, mat, vec, target_nrow)
}

cpp_capped_rne_find_actions <- function(U, v1, v2, U_hat, v1_hat, v2_hat, IC_holds, next_r1, next_r2, trans_mat, dest_rows, tie_breaking, tol = 1e-12) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_find_actions`, U, v1, v2, U_hat, v1_hat, v2_hat, IC_holds, next_r1, next_r2, trans_mat, dest_rows, tie_breaking, tol)
}

cpp_capped_rne_iterations <- function(T, sdf, rne, transmats, delta, rho, beta1, tie_breaking, tol = 1e-12, debug_row = -1L) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_iterations`, T, sdf, rne, transmats, delta, rho, beta1, tie_breaking, tol, debug_row)
}

cpp_capped_rne_multistage_iterations <- function(T, sdf, rne, transmats, static_rep_li, delta, rho, beta1, tie_breaking, tol = 1e-12, debug_row = -1L) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_multistage_iterations`, T, sdf, rne, transmats, static_rep_li, delta, rho, beta1, tie_breaking, tol, debug_row)
}

