# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_times_vec_rows <- function(mat, vec, vec_rows) {
    .Call(`_RelationalContractsCpp_mat_times_vec_rows`, mat, vec, vec_rows)
}

mat_times_vec <- function(mat, vec) {
    .Call(`_RelationalContractsCpp_mat_times_vec`, mat, vec)
}

cpp_capped_rne_find_actions <- function(U, v1, v2, U_hat, v1_hat, v2_hat, IC_holds, next_r1, next_r2, trans_mat, dest_rows, tie_breaking, tol = 1e-12) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_find_actions`, U, v1, v2, U_hat, v1_hat, v2_hat, IC_holds, next_r1, next_r2, trans_mat, dest_rows, tie_breaking, tol)
}

cpp_capped_rne_iterations <- function(T, sdf, rne, transmats, delta, rho, beta1, tie_breaking, tol = 1e-12, debug_row = -1L) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_iterations`, T, sdf, rne, transmats, delta, rho, beta1, tie_breaking, tol, debug_row)
}

cpp_capped_rne_multistage_iterations <- function(T, sdf, rne, transmats, static_rep_li, delta, rho, beta1, tie_breaking, tol = 1e-12, debug_row = -1L) {
    .Call(`_RelationalContractsCpp_cpp_capped_rne_multistage_iterations`, T, sdf, rne, transmats, static_rep_li, delta, rho, beta1, tie_breaking, tol, debug_row)
}

